In [8]:
import numpy as np

In [9]:
np.array([1, 3, 4])

array([1, 3, 4])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20, 0, -2)  # start, stop, step

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [12]:
np.array([1, 2, 3, 4, 5], dtype=np.str_)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [13]:
arr = np.array(["1", "2", "3", "4"], dtype=np.float32)

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [14]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [17]:
np.insert(arr, 2, [9, 10])

array([ 1.,  2.,  9., 10.,  3.,  4.], dtype=float32)

In [29]:
arr = np.arange(50)

arr[0::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
one = np.arange(0, 10, 1)
two = np.arange(30, 40, 1)
three = np.arange(90, 100, 1)
arr = np.array([one, two, three])

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
arr[:, -1]

array([ 9, 39, 99])

In [51]:
arr[1, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [53]:
arr[:, ::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [55]:
arr[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])