In [1]:
import numpy as np

In [2]:
np.array([1, 3, 4])

array([1, 3, 4])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(20, 0, -2)  # start, stop, step

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [5]:
np.array([1, 2, 3, 4, 5], dtype=np.str_)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
arr = np.array(["1", "2", "3", "4"], dtype=np.float32)

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [7]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [8]:
np.insert(arr, 2, [9, 10])

array([ 1.,  2.,  9., 10.,  3.,  4.], dtype=float32)

In [9]:
arr = np.arange(50)

arr[0::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [10]:
one = np.arange(0, 10, 1)
two = np.arange(30, 40, 1)
three = np.arange(90, 100, 1)
arr = np.array([one, two, three])

arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
arr[:, -1]

array([ 9, 39, 99])

In [12]:
arr[1, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
arr[:, ::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [14]:
arr[::-1, ::-1]

array([[99, 98, 97, 96, 95, 94, 93, 92, 91, 90],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [16]:
np.flip(arr, axis=1)

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.flip(arr, axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [20]:
np.flip(arr, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [34]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[5, 6], [7, 8], [9, 10]])

a.shape, b.shape

((3, 2), (3, 2))

In [35]:
np.hstack([a, b])  # Rows should be same

array([[ 1,  2,  5,  6],
       [ 3,  4,  7,  8],
       [ 5,  6,  9, 10]])

In [36]:
np.vstack([a, b])  # Columns should be same

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
# For h-stack the rows should be same

a = np.array([[1, 2], [3, 4], [5, 6]])  # 3 rows, 2 columns
b = np.array([[5, 6, 7], [7, 8, 9], [9, 10, 11]])  # 3 rows, 3 columns

# Here rows are same, so we can perform hstack
np.hstack([a, b])

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  7,  8,  9],
       [ 5,  6,  9, 10, 11]])

In [38]:
# For V-stack the columns should be same
a = np.array([[1, 2], [3, 4], [5, 6]])  # 3 rows, 2 columns
b = np.array([[5, 6], [7, 8], [9, 10], [11, 12]])  # 4 rows, 2 columns

np.vstack([a, b])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])