In [1]:
import numpy as np

In [5]:
"""
Given a NumPy array of shape (n,m). Add padding of a layer of 0’s on all 4 boundaries of the matrix.

Sample Input:
    [[3 2]
    [1 2]
    [3 4]
    [5 6]]

Sample Output:
    [[0 0 0 0]
     [0 1 2 0]
     [0 3 4 0]
     [0 5 6 0]
     [0 0 0 0]]
"""
arr = np.array([[3, 2], [1, 2], [3, 4], [5, 6]])

# Use np.pad to add padding
'''
pad_width       → how much to pad (e.g., 1 adds one layer around each edge).
mode            → how to fill those padded values.
constant_values → what number to use if mode is 'constant'.

Common mode options
   Mode	                                Description	                                      Example Output (for [1, 2, 3])
'constant'	    Pads with a constant value (default 0 unless changed via constant_values)	→ [0, 1, 2, 3, 0]
'edge'	        Repeats the edge values	                                                    → [1, 1, 2, 3, 3]
'reflect'	    Reflects values without repeating edge	                                    → [2, 1, 1, 2, 3, 3, 2]
'symmetric'	    Reflects including the edge	                                                → [1, 1, 2, 3, 3, 2, 1]
'wrap'	        Wraps values from the opposite edge	                                        → [3, 1, 2, 3, 1]
'mean',         'maximum', 'minimum', 'median'	Pads with the corresponding statistic of the array	(used less often)

'''
res = np.pad(arr, pad_width=1, constant_values=0)
res

array([[0, 0, 0, 0],
       [0, 3, 2, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 5, 6, 0],
       [0, 0, 0, 0]])