In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [31]:
# Add padding to given array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
# zeros = np.zeros(arr.shape[-1])
# new_arr = np.insert(arr, [0, len(arr)], [zeros, zeros], axis=0)
# new_arr
res = np.pad(arr, pad_width=1, mode="constant", constant_values=0)
res

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 0],
       [0, 5, 6, 7, 8, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
arr1 = np.insert(new_arr, [0, len(arr[0])], [0, 0], axis=1)
arr1

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 0],
       [0, 5, 6, 7, 8, 0],
       [0, 0, 0, 0, 0, 0]])