In [1]:
# from google.colab import drive

# drive.mount("/content/drive", force_remount=True)
# !ruff format "/content/drive/MyDrive/Colab Notebooks/numpy/numpy-1.ipynb" --line-length 120

In [2]:
import time

import numpy as np

# Speed Comparision b/w Python List and NumPy Arrays

In [3]:
# Using Python built-in List

speed_li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10_00_000
speed_li_len = len(speed_li)

start = time.perf_counter()
for i in range(speed_li_len):
    speed_li[i] = speed_li[i] * 2
end = time.perf_counter()

print("Time taken for Python list: ", end - start)

Time taken for Python list:  1.225168199998734


In [4]:
# Using NumPy

speed_li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 10_00_000
numpy_li = np.array(speed_li)

start = time.perf_counter()
result_li = numpy_li * 2
end = time.perf_counter()

print("Time taken for NumPy Arrays: ", end - start)

Time taken for NumPy Arrays:  0.020963899998605484


# Memory Usage b/w Python List and NumPy Arrays

In [5]:
import sys

memory_li = [i for i in range(100)]

memory_numpy = np.array(memory_li)

print("Size of Python List: ", sys.getsizeof(memory_li))
print("Size of NumPy array: ", memory_numpy.nbytes)
# print("Size of NumPy array: ", sys.getsizeof(memory_numpy))

Size of Python List:  920
Size of NumPy array:  800


# DataTypes b/w Python List and NumPy

In [6]:
types_li = [123, True, "abc", 4.5]
print("Python List with different types: ", types_li)

types_numpy = np.array(types_li)
print("NumPy Array with different types: ", types_numpy)

Python List with different types:  [123, True, 'abc', 4.5]
NumPy Array with different types:  ['123' 'True' 'abc' '4.5']


# Difference b/w Python List & NumPy Arrays
    **Feature**        |  **Python**     |  **NumPy**
    --------------------------------------------------------------    
    Speed              |  Slow           | Fast ( optimized in C )
    Data Types         |  Mixed allowed  | Same data types only
    Memory Efficiency  |  Less efficient | More efficient
    Math Operations    |  Manual loop    | Direct (vectorized)
    Built-in functions |  Limited        | More powerful tools

# Linear Algebra (Scalar, Vector, Matrix, Tensor)
*Scalar*: Single value, for e.g, 30 (Zero dimension)

*Vector*: 1 D-Array, for e.g, [1, 2, 3] (1 dimension)

*Matrix*: 2 or 3 D-Array, for e.g, [[1, 2, 3], [4, 5, 6]] (2 dimension)

*Tensor*: >3 D-Array, (greater than 3 dimensions)

In [7]:
# Scalar

scalar_np = np.array(30)
print("Shape of Array:", scalar_np.shape)
print("Dimensions of Array:", scalar_np.ndim)

Shape of Array: ()
Dimensions of Array: 0


In [8]:
# Vector

vector_np = np.array([1, 2, 3, 4, 5])
print("Shape of Array:", vector_np.shape)
print("Dimensions of Array:", vector_np.ndim)

Shape of Array: (5,)
Dimensions of Array: 1


In [9]:
# Matix

matrix_np = np.array([[1, 2], [3, 4], [5, 6]])
print("Shape of Array:", matrix_np.shape)
print("Dimensions of Array:", matrix_np.ndim)

Shape of Array: (3, 2)
Dimensions of Array: 2


# Creating Arrays in NumPy

In [10]:
# In Python using range

range_py = list(range(10))  # range(start, stop, step) e.g. range(1, 11, 1)
print(range_py)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
# In NumPy using arange

ranage_numpy = np.arange(10)  # arange(start, stop, step) e.g. arange(1, 11, 1)
print(ranage_numpy)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# Create evenly spaced numbers between given values

even_spaced_no = np.linspace(0, 1, 5)  # create 5 number between 0 and 1
print(even_spaced_no)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
# Logarithmic Scale Array

log_array = np.logspace(1, 3, 5)  # start, end, points ==> 10^1, 10^3, 5 points
print(log_array)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [14]:
# Array of Zeros (0)

zeros_array = np.zeros(10)  # creates an array with 10 zeros
print("Single Dimension:", zeros_array)

# Multi-dimension zeros
mul_zeros = np.zeros([2, 3], dtype=np.int32)  # 2 rows 3 columns of Zeros with type 32 bit integer
print("Multi Dimension:", mul_zeros)

Single Dimension: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Multi Dimension: [[0 0 0]
 [0 0 0]]


In [15]:
# Array of Ones (1)

ones_array = np.ones(5, dtype=int)  # Create an array with 5 ones of type int
print("Single Dimension:", ones_array)

# Multi-dimension ones
mul_ones = np.ones([2, 3])  # 2 rows 3 columns of ones
print("Multi Dimension:", mul_ones)

Single Dimension: [1 1 1 1 1]
Multi Dimension: [[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Array of custom values

cust_array = np.full(5, 2)  # Create an array with 5 two's
print("Single Dimension:", cust_array)

# Multi-dimension array
mul_array = np.full([4, 2], 7.1, dtype=np.int32)  # 4 rows 2 columns of array with number 7 of type 32 bit integer

# NOTE: The mul_array contains integer 7 even though I gave 7.1 (float). NumPy converted float to int32 because of dtype
print("Multi Dimension:", mul_array)

Single Dimension: [2 2 2 2 2]
Multi Dimension: [[7 7]
 [7 7]
 [7 7]
 [7 7]]


In [17]:
# Empty Array

empty_arr = np.empty  # Uninitialized Array
print("single dimension:", empty_arr)

# Multi dimension
mul_empty = np.empty([2, 3])  # Uninitialized Array with 2 rows and 3 columns

# NOTE: the mul_empty will contains zeros (0), but it is uninitialized array only
print("Multi Dimension:", mul_empty)

single dimension: <built-in function empty>
Multi Dimension: [[1. 1. 1.]
 [1. 1. 1.]]


# Random Values

In [18]:
single_rand = np.random.rand(2)  # Two random float values
print("Single Dimension:", single_rand)

mul_rand = np.random.rand(3, 4)  # 3 rows 4 columns of random values
print("Multi dimension:", mul_rand)

# Random Integer values
print()
rand_int = np.random.randint(10)  # This will generate only one value between 0 to given number
print("Single Dimension:", rand_int)
range_rand_int = np.random.randint(2, 99)
print("Random value b/w given range:", range_rand_int)
mul_rand_int = np.random.randint(2, 10, size=(2, 3))  # 2 rows 3 columns random value b/w 2 and 10
print("Multi Dimension:", mul_rand_int)

Single Dimension: [0.81370467 0.45668135]
Multi dimension: [[0.84890558 0.55943565 0.28788838 0.18305816]
 [0.93331254 0.15794391 0.7962862  0.81803745]
 [0.64956372 0.86733745 0.77056678 0.23385865]]

Single Dimension: 7
Random value b/w given range: 56
Multi Dimension: [[4 8 6]
 [9 7 6]]


In [19]:
# Standard Normal Distribution Random value
"""
    numpy.random.randn(d0, d1, ..., dn)

    Mean (Average)
        The mean is simply the average of all numbers.
        Add up all the numbers and divide by how many there are.
        Example: For the numbers 4, 8, 6, 5, 3, 7, the mean is ( 4 + 8 + 6 + 5 + 3 + 7 ) / 6 = 5.5.

    Variance
        Variance shows how spread out the numbers are from the mean.
        To find it, look at how far each number is from the mean, square each difference, then average those squared differences.
        Higher variance means numbers are more spread out, while low variance means they are closer together.

    Standard Deviation
        Standard deviation is simply the square root of the variance.
        It tells you, on average, how far each number is from the mean—but in the same units as the numbers (not squared).
        Smaller standard deviation means the numbers are close to the mean; bigger means they’re more spread out.

    Simple Example
      For the values 4, 8, 6, 5, 3, 7:
        - Mean = 5.5
        - Variance = 2.92 (the average of squared distances from the mean)
        - Standard deviation = 1.71 (the square root of 2.92).

    So, these three terms help describe the “center” (mean) and the “spread” (variance, standard deviation) of a set of numbers in a simple, meaningful way
"""

# If no arguments are provided, it returns a single random float sampled from the standard normal distribution
x = np.random.randn()  # Single random float
print("Single random float:", x)

# If you provide integers as arguments, it creates an array of the given shape filled with random values from the standard normal distribution
y = np.random.randn(5)  # 1D array (5 random numbers)
print("1D array:", y)

z = np.random.randn(3, 2)  # 2D array (3 rows, 2 columns)
print("2D array:", z)

# Each of these will draw values from the standard normal distribution (mean = 0, variance = 1)

Single random float: -0.46442637524273944
1D array: [-0.26147629 -0.44210466 -0.4797686  -0.40255389  1.11825219]
2D array: [[-1.67427274  0.04355084]
 [ 0.06184435  1.57408801]
 [ 0.38300087  1.05458164]]


In [20]:
# Custom Mean and Standard Deviation
# values = sigma * np.random.randn(shape) + mu
# Key Points
#     All numbers are generated independently.
#     The distribution is always "bell-shaped" (Gaussian), centered at 0, unless scaled as shown above

cust_mean = 2.5 * np.random.randn(2, 4) + 3  # creates a 2x4 array with mean 3 and std deviation 2.5
print("Custom Mean:", cust_mean)

Custom Mean: [[ 5.68621829 10.60455339  0.01272848  0.28193862]
 [ 3.36416411  2.39977583  6.06612875  1.7481847 ]]


# NumPy Data Types and Type Casting
    DataType |        Description         | Example Values
    --------- ---------------------------- ----------------
    int32    |   32-bit integer           | 1, 2, 3
    int64    |   64-bit integer (default) | 100, 2500
    float32  |   32-bit float             | 1.0, 3.14
    float64  |   64-bit float (default)   | 1.00000001
    bool     |   Boolean (True / False)   | True, False
    complex  |   Complex Numbers          | 1+2j, 3-4j
    str      |   Unicode String           | 'hi', '123'

NumPy arrays always have a single data type for all elements, so when mixed types are present, NumPy finds a type that can represent all elements safely—this is called "type upcasting" or "type promotion".

**Precedence Rules (Type Hierarchy)**

    - If all elements are integers (like ``), the array uses the smallest integer type that fits the values (usually int64 or int32).
    - If even one element is a float (like [1, 2, 3.5]), NumPy promotes everything to float (e.g., float64), because integer types cannot represent the decimal part.
    - If any element is a string (like [1, 2, 3, "hello"]), all values are converted to strings, since numeric types cannot hold text but strings can represent any value.
    - If there's a mix of more complex types (like a number and a Python object), NumPy uses the most general type, possibly object.

**Reason**

This system ensures that every value in the array can be represented correctly, even though it sometimes requires "widening" the type and possibly losing precision for some original data. The main idea: the "widest" or "most general" type takes precedence, with the order typically being integer < float < string/object.

**So**: floats win over ints, and strings win over both. That’s why adding one float makes the whole array float, and one string makes the entire array strings

In [21]:
# Default types (Based on the values NumPy will decide the type)

# Boolean values
bool_arr = np.array([True, False, True, False])
print("Boolean Array:", bool_arr)
print("Data Type:", bool_arr.dtype)

# Integer values
int_arr = np.array([1, 2, 3, 4, 5])  # As all the values are integers NumPy will use int64 which is default for integers
print("\nInteger Array:", int_arr)
print("Data Type:", int_arr.dtype)

# Float values
float_arr = np.array(
    [1.0, 2.5, 3.14, 4.0, 5.10]
)  # As all the values are floats NumPy will use float66 bit which is default for floats
print("\nFloat Array:", float_arr)
print("Data Type:", float_arr.dtype)

# exponential values
#   - The letter "e" or "E" to represent "times 10 to the power of," such as 1e3 or 1E3 for 1000[strictly speaking, e and E work interchangeably].
#   - The base is always 10; you don't typically change this number in scientific notation.
#   - The exponent can be positive (large numbers) or negative (small numbers).

# The notation "1e-9" means "1 times 10 to the power of -9." It is a way to write very small numbers using scientific notation. Specifically, 1e-9 equals 0.000000001 (one billionth)
# A positive exponent (like 1e + 9) means the number is large. You move the decimal point to the right by that many places. For example, 1e+3 = 1×10^3 = 1000.
# A negative exponent (like 1e − 9) means the number is very small, less than 1. You move the decimal point to the left by that many places. For example, 1e−3=1×10^−3=0.001.
exp_arr = np.array([1e-9, 1e8, 1e-7])  # As all the values are exponential NumPy will use float64 type
print("\nExponential Array:", exp_arr)
print("Data Type:", exp_arr.dtype)

# complex values
complex_arr = np.array([1 + 2j, 3 + 4j, 5 + 6j])  # As all the values are complex NumPy will use complex128 type
print("\nComplex Array:", complex_arr)
print("Data Type:", complex_arr.dtype)

# str values
str_arr = np.array(["a", "ball", "c", "dog"])  # As all the values are strings NumPy will use unicode type
print("\nString Array:", str_arr)
print("Data Type:", str_arr.dtype)

Boolean Array: [ True False  True False]
Data Type: bool

Integer Array: [1 2 3 4 5]
Data Type: int64

Float Array: [1.   2.5  3.14 4.   5.1 ]
Data Type: float64

Exponential Array: [1.e-09 1.e+08 1.e-07]
Data Type: float64

Complex Array: [1.+2.j 3.+4.j 5.+6.j]
Data Type: complex128

String Array: ['a' 'ball' 'c' 'dog']
Data Type: <U4


In [22]:
# Just Booleans
arr_data = np.array([True, False])
print("Boolean Array:", arr_data)
print("Data Type:", arr_data.dtype)

# Integer wins over booleans
print("\n***** Integer wins over booleans *****")
arr_data = np.array([False, 9, True, False])  # All booleans are converted to integers because of single int value
print("Booleans converted to Integers:", arr_data)
print("Data Type:", arr_data.dtype)

# Floats wins over Integers and booleans
print("\n***** Floats wins over Integers and booleans *****")
arr_data = np.array(
    [False, 2, True, 5, 9, 1.0, False]
)  # All bools and ints are converted to floats because of single float value
print("Booleans and Integers converted to Floats:", arr_data)
print("Data Type:", arr_data.dtype)

# Strings wins over Floats, Integers and Booleans
print("\n***** Strings wins over Floats, Integers and Booleans *****")
arr_data = np.array(
    [3.14, 786, True, 143, "Hi", False, 999.9]
)  # All bools, ints and floats are converted to str because of single str value
print("Strings wins over Floats, Integers and Booleans:", arr_data)
print("Data Type:", arr_data.dtype)

Boolean Array: [ True False]
Data Type: bool

***** Integer wins over booleans *****
Booleans converted to Integers: [0 9 1 0]
Data Type: int64

***** Floats wins over Integers and booleans *****
Booleans and Integers converted to Floats: [0. 2. 1. 5. 9. 1. 0.]
Data Type: float64

***** Strings wins over Floats, Integers and Booleans *****
Strings wins over Floats, Integers and Booleans: ['3.14' '786' 'True' '143' 'Hi' 'False' '999.9']
Data Type: <U32


In [23]:
# Manual convertion

# Convert all integer to floats
arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)  # Manually asking numpy to convert values to float64 bit
print("Integers are converted to floats:", arr)
print("Data Type:", arr.dtype)

# Convert all integer to bools
arr = np.array([1, 2, 0, 4, 0, -1], dtype=np.bool_)  # Manually asking numpy to convert values to bool
print("\nIntegers are converted to bools:", arr)
print("Data Type:", arr.dtype)

# Convert all numbers in string format to integers
arr = np.array(["1", "2", "3", "4", "5"], dtype=np.int32)  # Manually asking numpy to convert values to int32
print("\nStrings are converted to integers:", arr)
print("Data Type:", arr.dtype)

# Convert all numbers in string format to floats
arr = np.array(["3.14", "5.5", "10.1"], dtype=np.float32)  # Manually convert values to float32 type
print("\nStrings are converted to floats:", arr)
print("Data Type:", arr.dtype)

# Convert float like strings to integers
arr_int = arr.astype(np.int32)
print("\nFloats are converted to integers:", arr_int)
print("Data Type:", arr_int.dtype)

Integers are converted to floats: [1. 2. 3. 4. 5.]
Data Type: float64

Integers are converted to bools: [ True  True False  True False  True]
Data Type: bool

Strings are converted to integers: [1 2 3 4 5]
Data Type: int32

Strings are converted to floats: [ 3.14  5.5  10.1 ]
Data Type: float32

Floats are converted to integers: [ 3  5 10]
Data Type: int32


In [24]:
# Type casting errors
try:
    arr = np.array(["3.14", "5.5", "10.1"], dtype=np.int32)  # Trying to convert string like floats to int
except ValueError as e:
    print("Error:", e)

Error: invalid literal for int() with base 10: '3.14'


In [25]:
# Type casting errors

try:
    arr = np.array(["1", "hi", "123"], dtype=np.int32)  # Trying to convert strings to int
except ValueError as e:
    print("Error:", e)

Error: invalid literal for int() with base 10: 'hi'


# Insert new elements in existing array

In [26]:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# Append new elements at the end of the array
new_arr = np.append(arr, [6, 7, 8])
print("Array after appending new elements:", new_arr)

# Insert new elements in existing array
new_arr = np.insert(arr, 2, [10, 11])  # Insert 10 and 11 at index 2
print("Array after inserting new elements at index 2:", new_arr)

# Insert new elements in existing array
new_arr = np.insert(arr, [1, 3], [20, 30])  # Insert 20 at index 1 and 30 at index 3
print("Array after inserting new elements at index 1 and 3:", new_arr)

# Concatenate two arrays
arr2 = np.array([6, 7, 8])
concat_arr = np.concatenate((arr, arr2))
print("Concatenated Array:", concat_arr)

# Note: The original array remains unchanged after append, insert, and concatenate operations. These operations return new arrays with the modifications.s

Original Array: [1 2 3 4 5]
Array after appending new elements: [1 2 3 4 5 6 7 8]
Array after inserting new elements at index 2: [ 1  2 10 11  3  4  5]
Array after inserting new elements at index 1 and 3: [ 1 20  2  3 30  4  5]
Concatenated Array: [1 2 3 4 5 6 7 8]


# Delete elements in existing array

In [27]:
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

# Remove elements from array
new_arr = np.delete(arr, 2)  # Remove element at index 2
print("Array after deleting element at index 2:", new_arr)

# Remove multiple elements from array
new_arr = np.delete(arr, [1, 3])  # Remove elements at index 1 and 3
print("Array after deleting elements at index 1 and 3:", new_arr)

# Remove elements based on condition
new_arr = arr[arr % 2 == 0]  # Keep only even numbers
print("Array after removing odd numbers:", new_arr)

# Note: The original array remains unchanged after delete operations. These operations return new arrays with the modifications.

Original Array: [1 2 3 4 5]
Array after deleting element at index 2: [1 2 4 5]
Array after deleting elements at index 1 and 3: [1 3 5]
Array after removing odd numbers: [2 4]


# Important NumPy Array attributes

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 0, 0]])

# Find dimension of array
print("Array Dimension:", arr.ndim)  # also use np.ndim(arr)

# Find shape of array (no.of rows and columns)
print("Array Shape:", arr.shape)  # also use np.shape(arr)

# Find no.of elements in the array
print("Elements in array:", arr.size)  # also use np.size(arr)

# Find how much bytes of memory each element in the array takes
print("Memory of each element in bytes:", arr.itemsize)  # also use np.itemsize(arr)

# Sum of all elements in array
print("Sum of all elements:", arr.sum())  # also use np.sum(arr)

# Find minimum value in array
print("Minimum value in array:", arr.min())  # also use np.min(arr)

# Find maximum value in array
print("Maximum value in array:", arr.max())  # also use np.max(arr)

# Find average value in array
print("Average value in array:", arr.mean())  # also use np.mean(arr)

# Find standard deviation in array
print("Standard deviation in array:", arr.std())

Array Dimension: 2
Array Shape: (4, 3)
Elements in array: 12
Memory of each element in bytes: 8
Sum of all elements: 45
Minimum value in array: 0
Maximum value in array: 9
Average value in array: 3.75
Standard deviation in array: 3.112474899497183


# Array ReShaping

In [29]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Array values:", arr)
print("Original shape:", arr.shape)

# After reshaping
arr_reshape = arr.reshape(4, 2)  # converts into 4 rows and 2 columns
print("\nReshaped array:", arr_reshape)
print("Reshaped shape:", arr_reshape.shape)

arr_reshape = arr.reshape(2, 2, 2)  # converts into 2 rows and 2 columns
print("\nReshaped array:", arr_reshape)
print("Reshaped shape:", arr_reshape.shape)

# Flatten the reshaped array
arr_flatten = arr_reshape.flatten()
print("\nFlattened array:", arr_flatten)
print("Flattened shape:", arr_flatten.shape)

# Flatten array using ravel
arr_ravel = arr_reshape.ravel()
print("\nFlattened array using ravel:", arr_ravel)
print("Flattened shape using ravel:", arr_ravel.shape)

Array values: [1 2 3 4 5 6 7 8]
Original shape: (8,)

Reshaped array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Reshaped shape: (4, 2)

Reshaped array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Reshaped shape: (2, 2, 2)

Flattened array: [1 2 3 4 5 6 7 8]
Flattened shape: (8,)

Flattened array using ravel: [1 2 3 4 5 6 7 8]
Flattened shape using ravel: (8,)


# Difference b/w flatten and ravel

In [30]:
# Difference between flatten and ravel
# RAVEL: Changes made to ravel array will also reflect in original array
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Original array:", x)
print("Original shape:", x.shape)

y = x.ravel()
print("\nRavel array:", y)
print("Ravel shape:", y.shape)

# Modifying ravel array
y[0] = 111
print("\nModified ravel array:", y)
print("Modified original array:", x)

Original array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original shape: (2, 2, 2)

Ravel array: [1 2 3 4 5 6 7 8]
Ravel shape: (8,)

Modified ravel array: [111   2   3   4   5   6   7   8]
Modified original array: [[[111   2]
  [  3   4]]

 [[  5   6]
  [  7   8]]]


In [31]:
# FLATTEN: Flatten will do deep copy of array, any changes to flatten array will not effect origin array
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Original array:", x)
print("Original shape:", x.shape)

y = x.flatten()
print("\nFlattened array:", y)
print("Flattened shape:", y.shape)

# Modifying flatten array
y[0] = 111
print("\nModified flatten array:", y)
print("Modified original array:", x)

Original array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original shape: (2, 2, 2)

Flattened array: [1 2 3 4 5 6 7 8]
Flattened shape: (8,)

Modified flatten array: [111   2   3   4   5   6   7   8]
Modified original array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Arithmetic Operations on Arrays

NumPy allows to perform Mathamatical operations on entire array element by element wise without having to loop over the arrays

In [32]:
a = np.array([1, 2, 3])
b = np.array([7, 8, 9])

# Addition
arr_add = a + b  # 1 + 7, 2 + 8, 3 + 9
print("Array addition:", arr_add)

# Subtraction
arr_sub = b - a  # 7 - 1, 8 - 2, 9 - 3
print("Array subtraction:", arr_sub)

# Multiplication
arr_mul = a * b
print("Array multiplication:", arr_mul)

# Division
arr_div = b / a
print("Array division:", arr_div)

# Division with result in integer format
arr_div_int = b // a
print("Array division with integer result:", arr_div_int)

# Modulus
arr_mod = a % b
print("Array modulus:", arr_mod)

# Exponential
arr_exp = a**b
print("Array exponential:", arr_exp)

Array addition: [ 8 10 12]
Array subtraction: [6 6 6]
Array multiplication: [ 7 16 27]
Array division: [7. 4. 3.]
Array division with integer result: [7 4 3]
Array modulus: [1 2 3]
Array exponential: [    1   256 19683]


In [33]:
# Arithmetic Operations on single array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Addition
arr_add = arr + 5
print("Addition:", arr_add)

# Subtraction
arr_sub = arr - 2
print("Subtraction:", arr_sub)

# Multiplication
arr_mul = arr * 3
print("Multiplication:", arr_mul)

# Division
arr_div = arr / 2
print("Division:", arr_div)

Original array: [1 2 3 4 5]
Addition: [ 6  7  8  9 10]
Subtraction: [-1  0  1  2  3]
Multiplication: [ 3  6  9 12 15]
Division: [0.5 1.  1.5 2.  2.5]


In [34]:
# Universal functions

arr = np.array([1, 5.5, 9.9, 17])
print("Original array:", arr)

# Square root
arr_sqrt = np.sqrt(arr)
print("Square root:", arr_sqrt)

# Exponential
arr_exp = np.exp(arr)
print("Exponential:", arr_exp)

# Logarithmic
arr_log = np.log(arr)
print("Logarithmic:", arr_log)

# Sin
arr_sign = np.sin(arr)
print("Sin:", arr_sign)

# Absolute value
arr_abs = np.abs(arr)
print("Absolute value:", arr_abs)

Original array: [ 1.   5.5  9.9 17. ]
Square root: [1.         2.34520788 3.14642654 4.12310563]
Exponential: [2.71828183e+00 2.44691932e+02 1.99303704e+04 2.41549528e+07]
Logarithmic: [0.         1.70474809 2.29253476 2.83321334]
Sin: [ 0.84147098 -0.70554033 -0.45753589 -0.96139749]
Absolute value: [ 1.   5.5  9.9 17. ]


# Indexing & Slicing

In [35]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

"""
array[start:stop:step]
  start: index to start from (inclusive)
  stop: index to stop at (exclusive)
  step: how many elements to skip
From the beginning to the end with a step of 1

    arr[0:len(arr):1]
            (or)
    arr[0::1]
            (or)
    arr[:]
            (or)
    arr[::]
"""

print("\n***** Indexing *****")
print("First element arr[0]:", arr[0])
print("Second element arr[1]:", arr[1])
print("Last element arr[-1]:", arr[-1])
print("Last element using len arr[len(arr) - 1]:", arr[len(arr) - 1])

# Slicing [start, stop, step]
print("\n***** Slicing *****")
print("First 3 elements arr[:3]:", arr[:3])  # Means all the elements from index 0 to 3
print("Exclude first 2 elements arr[2:]:", arr[2:])  # Means all the elements from index 2 to end
print("Middle elements arr[1:4]:", arr[1:4])  # Means all the elements from index 1 to 4
print("Last 3 elements arr[-3::1]:", arr[-3::1])
print("Reverse array arr[::-1]:", arr[::-1])

Original array: [1 2 3 4 5]

***** Indexing *****
First element arr[0]: 1
Second element arr[1]: 2
Last element arr[-1]: 5
Last element using len arr[len(arr) - 1]: 5

***** Slicing *****
First 3 elements arr[:3]: [1 2 3]
Exclude first 2 elements arr[2:]: [3 4 5]
Middle elements arr[1:4]: [2 3 4]
Last 3 elements arr[-3::1]: [3 4 5]
Reverse array arr[::-1]: [5 4 3 2 1]


In [36]:
# Multi-Dimension array
one = np.arange(0, 10, 1)
two = np.arange(30, 40, 1)
three = np.arange(90, 100, 1)
arr = np.array([one, two, three])
print("Original array:", arr)

# Indexing
print("\n***** Indexing *****")
print("First row arr[0]:", arr[0])
print("First element of first row:", arr[0][0])
print("Last element in the last row:", arr[-1][-1])

# Slicing
print("\n***** Slicing *****")
print("First 2 rows:", arr[:2])
print("Last 2 columns from last 2 rows:", arr[1:, 1:])  # [[5, 6], [8, 9]]
print("Last columns in each row:", arr[:, -1])
print("Reverse all columns:", arr[:, ::-1])
print("Reverse all rows:", arr[::-1, :])
print("Reverse both rows and columns:", arr[::-1, ::-1])
print("Get first 5 columns of all rows:", arr[:, 0:5])
print("Get every other column of all rows:", arr[:, ::2])

# Index Arrays
index = [0, 2]
# np.take is built in function to perform indexing and slicing
print("\n***** Index Arrays *****")
print("First and last rows using np.take:", np.take(arr, index, axis=0))
print("First and last columns using np.take:", np.take(arr, index, axis=1))

Original array: [[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]
 [90 91 92 93 94 95 96 97 98 99]]

***** Indexing *****
First row arr[0]: [0 1 2 3 4 5 6 7 8 9]
First element of first row: 0
Last element in the last row: 99

***** Slicing *****
First 2 rows: [[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]]
Last 2 columns from last 2 rows: [[31 32 33 34 35 36 37 38 39]
 [91 92 93 94 95 96 97 98 99]]
Last columns in each row: [ 9 39 99]
Reverse all columns: [[ 9  8  7  6  5  4  3  2  1  0]
 [39 38 37 36 35 34 33 32 31 30]
 [99 98 97 96 95 94 93 92 91 90]]
Reverse all rows: [[90 91 92 93 94 95 96 97 98 99]
 [30 31 32 33 34 35 36 37 38 39]
 [ 0  1  2  3  4  5  6  7  8  9]]
Reverse both rows and columns: [[99 98 97 96 95 94 93 92 91 90]
 [39 38 37 36 35 34 33 32 31 30]
 [ 9  8  7  6  5  4  3  2  1  0]]
Get first 5 columns of all rows: [[ 0  1  2  3  4]
 [30 31 32 33 34]
 [90 91 92 93 94]]
Get every other column of all rows: [[ 0  2  4  6  8]
 [30 32 34 36 

In [37]:
# Some questions on Slicing and Indexing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Given array:", arr)

# 1. Given a 2D array how would you extract the second row only?
print("\n***** 1. Given a 2D array how would you extract the second row only? *****")
print("Using indexing:", arr[1])
print("Using slicing:", arr[1:2][0])

# 2. Using the same array, how would you extract the third column?
print("\n***** 2. Using the same array, how would you extract the third column? *****")
print("Using indexing:", arr[1][2])
print("Using slicing:", arr[1:2, 2:3][0][0])

print(arr[::2, ::2])

Given array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

***** 1. Given a 2D array how would you extract the second row only? *****
Using indexing: [5 6 7 8]
Using slicing: [5 6 7 8]

***** 2. Using the same array, how would you extract the third column? *****
Using indexing: 7
Using slicing: 7
[[ 1  3]
 [ 9 11]]


# Iterating NumPy Arrays

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:", arr)

# Iterating over rows
print("\n***** Iterating over rows using nditer *****")
for x in np.nditer(arr):
    print(x, end=" ")

# Iterating over array also get indexs
print("\n\n***** Iterating over rows using ndenumerate *****")
for idx, x in np.ndenumerate(arr):
    print(f"Index {idx} has value {x}")

# Traditional loop
print("\n***** Traditional loop *****")
for row in arr:
    for col in row:
        print(col, end=", ")
    print()

Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

***** Iterating over rows using nditer *****
1 2 3 4 5 6 7 8 9 

***** Iterating over rows using ndenumerate *****
Index (0, 0) has value 1
Index (0, 1) has value 2
Index (0, 2) has value 3
Index (1, 0) has value 4
Index (1, 1) has value 5
Index (1, 2) has value 6
Index (2, 0) has value 7
Index (2, 1) has value 8
Index (2, 2) has value 9

***** Traditional loop *****
1, 2, 3, 
4, 5, 6, 
7, 8, 9, 


# Views vs Copies

In [39]:
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Copy (Original array will not get effected)
arr_copy = arr.copy()
arr_copy[0] = 99
print("\nCopy of array:", arr_copy)
print("Original array:", arr)

# View (Will change the original array)
arr_view = arr.view()
arr_view[0] = 99
print("\nView of array:", arr_view)
print("Original array:", arr)


# View 2 (Will change the original array)
arr = np.array([1, 2, 3, 4, 5])
arr_view = arr[::]
arr_view[0] = 99
print("\nOriginal array:", arr)
print("View of array:", arr_view)

Original array: [1 2 3 4 5]

Copy of array: [99  2  3  4  5]
Original array: [1 2 3 4 5]

View of array: [99  2  3  4  5]
Original array: [99  2  3  4  5]

Original array: [99  2  3  4  5]
View of array: [99  2  3  4  5]


# Transpose

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:", arr)

# Transpose (flips rows to columns and "Visa Versa")
arr_transpose = arr.transpose()
print("\n***** Array Transpose *****")
print("Transpose of array:", arr_transpose)

# Swap axis
arr = np.array([[[1, 2], [3, 4], [5, 6]]])
print("\n***** Swap Array *****")
print("Original array:", arr)
print("Original shape:", arr.shape)

# Swap axis 0 (zero) with axis 1
arr_swap = np.swapaxes(arr, 0, 1)
print("\n***** Swap axis 0 (zero) with axis 1 *****")
print("Swapped array:", arr_swap)
print("Swapped shape:", arr_swap.shape)

# Swap axis 0 (zero) with axis 2
arr_swap = np.swapaxes(arr, 0, 2)
print("\n***** Swap axis 0 (zero) with axis 2 *****")
print("Swapped 2 array:", arr_swap)
print("Swapped 2 shape:", arr_swap.shape)

# Swap axis 1 with axis 2
arr_swap = np.swapaxes(arr, 1, 2)
print("\n***** Swap axis 1 with axis 2 *****")
print("Swapped 3 array:", arr_swap)
print("Swapped 3 shape:", arr_swap.shape)

Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]

***** Array Transpose *****
Transpose of array: [[1 4 7]
 [2 5 8]
 [3 6 9]]

***** Swap Array *****
Original array: [[[1 2]
  [3 4]
  [5 6]]]
Original shape: (1, 3, 2)

***** Swap axis 0 (zero) with axis 1 *****
Swapped array: [[[1 2]]

 [[3 4]]

 [[5 6]]]
Swapped shape: (3, 1, 2)

***** Swap axis 0 (zero) with axis 2 *****
Swapped 2 array: [[[1]
  [3]
  [5]]

 [[2]
  [4]
  [6]]]
Swapped 2 shape: (2, 3, 1)

***** Swap axis 1 with axis 2 *****
Swapped 3 array: [[[1 3 5]
  [2 4 6]]]
Swapped 3 shape: (1, 2, 3)


# Concatenation

In [41]:
a = np.array([1, 2])
b = np.array([3, 4])
print("Array a:", a)
print("Array b:", b)

# Concatenate
arr_concat = np.concatenate((a, b))
print("\n***** Concatenate *****")
print("Concatenated array:", arr_concat)

# Vertical stack concatenation
arr_vstack = np.vstack((a, b))  # np.stack((a, b), axis = 0)
print("\n***** Vertical stack concatenation *****")
print("Vertical stack concatenation:", arr_vstack)

# Horizontal stack concatenation
arr_hstack = np.hstack((a, b))  # np.stack((a, b), axis = 1)
print("\n***** Horizontal stack concatenation *****")
print("Horizontal stack concatenation:", arr_hstack)

Array a: [1 2]
Array b: [3 4]

***** Concatenate *****
Concatenated array: [1 2 3 4]

***** Vertical stack concatenation *****
Vertical stack concatenation: [[1 2]
 [3 4]]

***** Horizontal stack concatenation *****
Horizontal stack concatenation: [1 2 3 4]


In [42]:
# Concat arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Array Concatenation
concat = np.concatenate((x, y))
print("Array Concatenation:", concat)

# V-Stack Array
arr_v = np.vstack((x, y))
print("Array V-stack:", arr_v)

# H-Stack Array
arr_h = np.hstack((x, y))
print("Array H-stack:", arr_h)

# Flatten Array
# arr_flat = np.flatiter(arr_h)
# print("Array Flat:", arr_flat)

Array Concatenation: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array V-stack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array H-stack: [[1 2 5 6]
 [3 4 7 8]]


# Split Arrays

In [43]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("Original array:", arr)

# Split Array into 2
print("\n***** Split Array into 2 *****")
arr_split = np.split(arr, 2)
print("Split array:", arr_split)

# Split Array into 4
print("\n***** Split Array into 4 *****")
arr_split = np.split(arr, 4)
print("Split array:", arr_split)

# Horizontal split into 2
print("\n***** Horizontal split into 2 *****")
arr_split = np.hsplit(arr, 2)  # As the array has only 2 columns, it is only possible to split into 2
print("Horizontal Split array:", arr_split)

# Horizontal split into 4
# print("\n***** Horizontal split into 4 *****")
# arr_split = np.hsplit(arr, 4)
# print("Horizontal Split array:", arr_split)

# Vertical split into 4
print("\n***** Vertical split into 4 *****")
arr_split = np.vsplit(arr, 4)
print("Vertical Split array:", arr_split)

# Vertical split into 2
print("\n***** Vertical split into 2 *****")
arr_split = np.vsplit(arr, 2)
print("Vertical Split array:", arr_split)

Original array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

***** Split Array into 2 *****
Split array: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

***** Split Array into 4 *****
Split array: [array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

***** Horizontal split into 2 *****
Horizontal Split array: [array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]

***** Vertical split into 4 *****
Vertical Split array: [array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

***** Vertical split into 2 *****
Vertical Split array: [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# Repeating and tailing

In [44]:
print("***** Repeating and Tailing ****")
arr = np.array([1, 2, 3])
print("Original array:", arr)

print("\nRepeating Array")
arr_rep = np.repeat(arr, 2)  # Repeat arr 2 times
print("Repeating Array:", arr_rep)

print("\nTailing Array")
arr_tail = np.tile(arr, 2)
print("Tailing Array:", arr_tail)

***** Repeating and Tailing ****
Original array: [1 2 3]

Repeating Array
Repeating Array: [1 1 2 2 3 3]

Tailing Array
Tailing Array: [1 2 3 1 2 3]


# Aggregate Functions

In [45]:
print("***** Aggregate Functions *****")
arr = np.array([1, 2, 3])
print("Original array:", arr)

# Sum of array
arr_sum = np.sum(arr)
print("\nSum of array:", arr_sum)

# Mean of array
arr_mean = np.mean(arr)
print("\nMean of array:", arr_mean)

# Median of array
arr_median = np.median(arr)
print("\nMedian of array:", arr_median)

# Standard deviation
arr_std = np.std(arr)
print("\nStandard deviation (std) of array:", arr_std)

# variant
arr_var = np.var(arr)
print("\nVariance of array:", arr_var)

# Minimum number in array
arr_min = np.min(arr)
print("\nMinimum of array:", arr_min)

# Maximum number in array
arr_max = np.max(arr)
print("\nMaximum of array:", arr_max)

***** Aggregate Functions *****
Original array: [1 2 3]

Sum of array: 6

Mean of array: 2.0

Median of array: 2.0

Standard deviation (std) of array: 0.816496580927726

Variance of array: 0.6666666666666666

Minimum of array: 1

Maximum of array: 3


In [46]:
print("***** Aggregate Functions in 2D array *****")
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("Original array:", arr)

# Sum of array in x-axis
arr_sum = np.sum(arr, axis=0)
print("\nSum of array in x-axis:", arr_sum)

# Sum of array in y-axis
arr_sum = np.sum(arr, axis=1)
print("\nSum of array in y-axis:", arr_sum)

***** Aggregate Functions in 2D array *****
Original array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Sum of array in x-axis: [16 20]

Sum of array in y-axis: [ 3  7 11 15]


# Cumulative Operations

In [47]:
arr = np.array([1, 2, 3])
print("Original array:", arr)

# Running sum
arr_sum = np.cumsum(arr)
print("\nRunning sum:", arr_sum)

# Running prod
arr_prod = np.cumprod(arr)
print("\nRunning product:", arr_prod)

Original array: [1 2 3]

Running sum: [1 3 6]

Running product: [1 2 6]


# Conditional Based Operations

In [48]:
arr = np.array([10, 3, 17, 9, 2, 15, 4, 6, 12, 0, 11])
print("Original array:", arr)

# Less than Where condition
print("\n***** Where Condition *****")
arr_where = np.where(
    arr < 5, "low", "high"
)  # No less than 5 will be shown as low and grater than 5 will be shown as high
print("Less than Where cond:", arr_where)

# Even Numbers condition
arr_even = np.where(arr % 2 == 0, "even", "odd")
print("\nEven or odd condition:", arr_even)


# Arg Where condition
print("\n***** Arg Where condition *****")
arr_where = np.argwhere(arr > 5)
print("Less than Arg Where cond:", arr_where)

# Advance Conditions
print("\n***** Logical AND condition *****")
arr_logi = np.logical_and(arr > 3, arr < 13)
print("\nLogical AND condition:", arr_logi)

Original array: [10  3 17  9  2 15  4  6 12  0 11]

***** Where Condition *****
Less than Where cond: ['high' 'low' 'high' 'high' 'low' 'high' 'low' 'high' 'high' 'low' 'high']

Even or odd condition: ['even' 'odd' 'odd' 'odd' 'even' 'odd' 'even' 'even' 'even' 'even' 'odd']

***** Arg Where condition *****
Less than Arg Where cond: [[ 0]
 [ 2]
 [ 3]
 [ 5]
 [ 7]
 [ 8]
 [10]]

***** Logical AND condition *****

Logical AND condition: [ True False False  True False False  True  True  True False  True]


In [49]:
# Multi dimension arr conditional operations
print("********** Multi dimension arr conditional operations **********")
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:", arr)

# This will give row wise column index result, like 6 is in 1 row and 2 element [1, 2]
arr_where = np.argwhere(arr > 5)
print("Less than Arg Where cond:", arr_where)

# The logical OR consider all the elements in the entire row
arr_logi_or = np.logical_or(arr > 3, arr < 7)
print("\nLogical OR condition:", arr_logi_or)

arr_logic_and = np.logical_and(arr > 3, arr < 7)
print("\nLogical AND condition:", arr_logic_and)

********** Multi dimension arr conditional operations **********
Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Less than Arg Where cond: [[1 2]
 [2 0]
 [2 1]
 [2 2]]

Logical OR condition: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Logical AND condition: [[False False False]
 [ True  True  True]
 [False False False]]


In [50]:
# Fetch the values that satisfy the condition
print("\n***** Fetch the values that satisfy the condition *******")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

# Fetch values that are greater than 5
mask = np.where(arr > 5)
arr_gt_5 = arr[mask]
print("\nValues greater than 5:", arr_gt_5)

# Fetch values are greater than 3 and lesser than 7
mask = np.logical_and(arr > 3, arr < 7)
arr_gt_3 = arr[mask]
print("\nValues 3 > arr < 7:", arr_gt_3)


***** Fetch the values that satisfy the condition *******
Original array: [1 2 3 4 5 6 7 8 9]

Values greater than 5: [6 7 8 9]

Values 3 > arr < 7: [4 5 6]


# Broadcasting
In NumPy, broadcasting is the set of rules that allows arrays with different shapes to be used together in arithmetic operations. NumPy automatically `stretches` or `duplicates` the smaller array along certain dimensions to match the shape of the larger array, enabling element-wise operations without explicitly writing slow Python loops or creating large temporary arrays.

### Broadcasting Rules
**NOTE**: NumPy compares the shapes of the arrays from the end (right to left) and checks following rules:-
1. *Check Dimensions*: Ensure the arrays have the same number of dimensions or expandable dimensions.
2. *Dimension Padding*: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
3. *Shape Compatibility*: Two dimensions are compatible if they are equal or one of them is 1.

If these conditions aren't met NumPy will raise a ValueError

In [51]:
# Example 1: Broadcasting a Scalar to a 1D Array

arr = np.array([10, 20, 30])
scalar_arr = 5

# The scalar_arr will be stretched to (1, 3) shape [5, 5, 5] and performs the operation
res = arr + scalar_arr
# [10, 20, 30] + [5, 5, 5] = [10+5, 20+5, 30+5] ==== [15, 25, 35]
print("Addition:", res)

Addition: [15 25 35]


In [52]:
# Example 2: Broadcasting a 1D Array to a 2D Array

a1 = np.array([10, 10, 10])
a2 = np.array([[2, 2, 2], [1, 1, 1], [0, 0, 0]])

res = a1 + a2
# NumPy stretches `a1` to [[10, 10, 10], [10, 10, 10], [10, 10, 10]] and performs addition
print("Addition:", res)

Addition: [[12 12 12]
 [11 11 11]
 [10 10 10]]


In [53]:
np.broadcast_shapes((3, 1), (1, 4))

(3, 4)