In [1]:
import numpy as np

In [2]:
# Concat arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Array Concatenation
concat = np.concatenate((x, y))
print("Array Concatenation:", concat)

# V-Stack Array
arr_v = np.vstack((x, y))
print("Array V-stack:", arr_v)

# H-Stack Array
arr_h = np.hstack((x, y))
print("Array H-stack:", arr_h)

# Flatten Array
# arr_flat = np.flatiter(arr_h)
# print("Array Flat:", arr_flat)

Array Concatenation: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array V-stack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array H-stack: [[1 2 5 6]
 [3 4 7 8]]


# Repeating & Tailing

In [3]:
print("***** Repeating and Tailing ****")
arr = np.array([1, 2, 3])
print("Original array:", arr)

print("\nRepeating Array")
arr_rep = np.repeat(arr, 2)  # Repeat arr 2 times
print("Repeating Array:", arr_rep)

print("\nTailing Array")
arr_tail = np.tile(arr, 2)
print("Tailing Array:", arr_tail)

***** Repeating and Tailing ****
Original array: [1 2 3]

Repeating Array
Repeating Array: [1 1 2 2 3 3]

Tailing Array
Tailing Array: [1 2 3 1 2 3]


# Aggregate Functions

In [4]:
print("***** Aggregate Functions *****")
arr = np.array([1, 2, 3])
print("Original array:", arr)

# Sum of array
arr_sum = np.sum(arr)
print("\nSum of array:", arr_sum)

# Mean of array
arr_mean = np.mean(arr)
print("\nMean of array:", arr_mean)

# Median of array
arr_median = np.median(arr)
print("\nMedian of array:", arr_median)

# Standard deviation
arr_std = np.std(arr)
print("\nStandard deviation (std) of array:", arr_std)

# variant
arr_var = np.var(arr)
print("\nVariance of array:", arr_var)

# Minimum number in array
arr_min = np.min(arr)
print("\nMinimum of array:", arr_min)

# Maximum number in array
arr_max = np.max(arr)
print("\nMaximum of array:", arr_max)

***** Aggregate Functions *****
Original array: [1 2 3]

Sum of array: 6

Mean of array: 2.0

Median of array: 2.0

Standard deviation (std) of array: 0.816496580927726

Variance of array: 0.6666666666666666

Minimum of array: 1

Maximum of array: 3


In [5]:
print("***** Aggregate Functions in 2D array *****")
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("Original array:", arr)

# Sum of array in x-axis
arr_sum = np.sum(arr, axis=0)
print("\nSum of array in x-axis:", arr_sum)

# Sum of array in y-axis
arr_sum = np.sum(arr, axis=1)
print("\nSum of array in y-axis:", arr_sum)

***** Aggregate Functions in 2D array *****
Original array: [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Sum of array in x-axis: [16 20]

Sum of array in y-axis: [ 3  7 11 15]


# Cumulative Operations

In [6]:
arr = np.array([1, 2, 3])
print("Original array:", arr)

# Running sum
arr_sum = np.cumsum(arr)
print("\nRunning sum:", arr_sum)

# Running prod
arr_prod = np.cumprod(arr)
print("\nRunning product:", arr_prod)

Original array: [1 2 3]

Running sum: [1 3 6]

Running product: [1 2 6]


# Conditional Based Operations

In [7]:
arr = np.array([10, 3, 17, 9, 2, 15, 4, 6, 12, 0, 11])
print("Original array:", arr)

# Less than Where condition
print("\n***** Where Condition *****")
arr_where = np.where(
    arr < 5, "low", "high"
)  # No less than 5 will be shown as low and grater than 5 will be shown as high
print("Less than Where cond:", arr_where)

# Even Numbers condition
arr_even = np.where(arr % 2 == 0, "even", "odd")
print("\nEven or odd condition:", arr_even)


# Arg Where condition
print("\n***** Arg Where condition *****")
arr_where = np.argwhere(arr > 5)
print("Less than Arg Where cond:", arr_where)

# Advance Conditions
print("\n***** Logical AND condition *****")
arr_logi = np.logical_and(arr > 3, arr < 13)
print("\nLogical AND condition:", arr_logi)

Original array: [10  3 17  9  2 15  4  6 12  0 11]

***** Where Condition *****
Less than Where cond: ['high' 'low' 'high' 'high' 'low' 'high' 'low' 'high' 'high' 'low' 'high']

Even or odd condition: ['even' 'odd' 'odd' 'odd' 'even' 'odd' 'even' 'even' 'even' 'even' 'odd']

***** Arg Where condition *****
Less than Arg Where cond: [[ 0]
 [ 2]
 [ 3]
 [ 5]
 [ 7]
 [ 8]
 [10]]

***** Logical AND condition *****

Logical AND condition: [ True False False  True False False  True  True  True False  True]


In [8]:
# Multi dimension arr conditional operations
print("********** Multi dimension arr conditional operations **********")
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:", arr)

# This will give row wise column index result, like 6 is in 1 row and 2 element [1, 2]
arr_where = np.argwhere(arr > 5)
print("Less than Arg Where cond:", arr_where)

# The logical OR consider all the elements in the entire row
arr_logi_or = np.logical_or(arr > 3, arr < 7)
print("\nLogical OR condition:", arr_logi_or)

arr_logic_and = np.logical_and(arr > 3, arr < 7)
print("\nLogical AND condition:", arr_logic_and)

********** Multi dimension arr conditional operations **********
Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Less than Arg Where cond: [[1 2]
 [2 0]
 [2 1]
 [2 2]]

Logical OR condition: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Logical AND condition: [[False False False]
 [ True  True  True]
 [False False False]]


In [9]:
# Fetch the values that statisfy the condition
print("\n***** Fetch the values that statisfy the condition *******")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

# Fetch values that are greater than 5
mask = np.where(arr > 5)
arr_gt_5 = arr[mask]
print("\nValues greater than 5:", arr_gt_5)

# Fetch values are greater than 3 and lesser than 7
mask = np.logical_and(arr > 3, arr < 7)
arr_gt_3 = arr[mask]
print("\nValues 3 > arr < 7:", arr_gt_3)


***** Fetch the values that statisfy the condition *******
Original array: [1 2 3 4 5 6 7 8 9]

Values greater than 5: [6 7 8 9]

Values 3 > arr < 7: [4 5 6]
